### ISSUE TITLE
Timers call the node twice in a row when the time hits.

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#109]
---
This is an item logged from the To-Do and was originally reported by (@CelticMinstrel?). If you are familiar with or can recreate this bug, please provide details here.

**Comment by NQNStudios** [comment]
Do 4eb9be21c695b1015ff123f0b2280c4554da43fd and c7f4cee68495c79b05ba90dea3abf71902f69459 fix this?

**Comment by CelticMinstrel** [comment]
Yes, it looks that way.
