### ISSUE TITLE
Using the Character Editor on a save seems to automatically remove the party from the scenario.

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#115]
ADoS later reported that this in fact happens whenever loading a saved game.

---
This is an item logged from the To-Do and was originally reported by ADoS. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment]
Given that I just recently loaded the saved game for #111, I'm pretty confident in saying that this is not currently an issue.
