### ISSUE TITLE
Outdoor wandering monsters are invisible

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#125]
---
This is an item logged from the To-Do and was originally reported by Tados. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment]
I think this might've been fixed? Not sure.

**Comment by CelticMinstrel** [comment]
Might be a duplicate of #237

**Comment by CelticMinstrel** [comment]
It does look like it might be, but I can't be certain, mainly because this one is too sparsely described.

But then again, there isn't really a point in having an issue open if we don't even know what the issue is, so I guess I'll close it.
