### ISSUE TITLE
placing multi-space object in scenario editor doesn't trigger adjusting

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#143]
---
This is an item logged from the To-Do and was originally reported by (@CelticMinstrel?). If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment]
A way to trigger this (assuming it hasn't been fixed already) might be to fill an area with hills, then drop a grass two-space rubble in the middle. The expected behaviour is that the hills surrounding the two rubble spaces turn into the appropriate trims.

**Comment by CelticMinstrel** [comment]
I just did the above test and confirmed that surrounding terrain _is_ adjusted properly. However, it's still not handled properly if you substitute mountains for hills in the above test. Still, I think that can be filed as a separate issue.
