### ISSUE TITLE
Main splash screen goes in wrong place in fullscreen mode

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#147]
---
This is an item logged from the To-Do and was originally reported by (@CelticMinstrel?). If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment]
99.99% certain that this was fixed when I implemented the zooming display mode.

**Comment by CelticMinstrel** [comment]
Works fine on Windows a few commits back from 03c19fa.
