### ISSUE TITLE
Add formatting flags for text strings.

### ISSUE THREAD

**Issue by sylae** [calref/cboe#16]
_Original author: celtic.m...@gmail.com (April 26, 2009 01:46:24)_

One thing I've been thinking about is string lengths. Currently, the game
can't handle strings longer than 255 characters, because the str_len arrays
holding the string lengths are of type unsigned char. If we changed it to
unsigned short, it could handle strings of up to 65535 characters; however,
I think that's a bit much. So, I though we could restrict it a little more,
but make up for that by including format flags. For example, if we were
fine with restricting the string length to 1023 characters, we would have 6
unused bits available for formatting.

The most significant bit, then, could indicate that the string should be
drawn framed. That would be simple to implement – you'd just have to set
the item flag to 1 in cd_create_custom_dialog. The next three bits could
specify that the text be drawn in colour – one bit for red, one for green,
one for blue. And the next 2 bits could specify that the text be indented.

Such a change would not have to wait for the format rewrite – adding it
would not actually affect legacy compatibility. However, it would be
impossible to use until the scenario file format supports it. I'm just
putting it forth as an idea. Actually, I think I'll also add it to the
Google Code issues page so that it's not forgotten.

If the change is implemented, and size represents the string length, then:
- whether it is framed would be &quot;size &amp; 32768&quot;,
- the colour would be &quot;(size &amp; 28672) &gt;&gt; 12&quot;,
- the indent would be &quot;(size &amp; 3072) &gt;&gt; 10&quot;, and
- the actual length would be &quot;size &amp; 1023&quot;,
  if my calculations are correct.

Colours would be:
0 – grey (because black would be invisible against the background,
1 – blue,
2 – green,
3 – cyan,
4 – red,
]5 – magenta,
6 – yellow,
7 – white.

Indents would be something like:
0 – none,
1 – 10 pixels,
2 – 15 pixels,
3 – 20 pixels.
That could vary depending on which values work well.[/spoiler]

_Original issue: http://code.google.com/p/openexile/issues/detail?id=4_

**Comment by CelticMinstrel** [comment]
String lengths are now essentially unlimited as they use std::string for storage; however, there's no allowance for formatting, so that's still something to consider. I do like the idea of allowing for formatting.

**Comment by NQNStudios** [comment]
With all the errors we've had around measuring text, wrapping text and having to cache the wrapping info, relative positioning, highlighting, I would estimate this as a high-risk change. Since it wouldn't add anything to the scenarios that already exist, and no one is currently making new scenarios, I would recommend that we triage this one.
