### ISSUE TITLE
Looking at a road crossing a trim yields "Hills" instead of "Road".

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#162]
---
This is an item logged from the To-Do and was originally reported by (@CelticMinstrel?). If you are familiar with or can recreate this bug, please provide details here

**Comment by CelticMinstrel** [comment]
I suspect it might say _both_ now, but need to check that.

**Comment by CelticMinstrel** [comment]
Confirmed, at 03c19fa it prints both road and hills.
