### ISSUE TITLE
Scrollbar and done button in shops doesn't work

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#165]
---
This is an item logged from the To-Do and was originally reported by (@CelticMinstrel?). If you are familiar with or can recreate this bug, please provide details here

**Comment by CelticMinstrel** [comment]
I seem to recall fixing this, but I'm not quite sure. (It might've been related to the `ul` global that I refactored away when implementing the 2x view mode?)

**Comment by CelticMinstrel** [comment]
Confirmed working at  03c19fa.
