### ISSUE TITLE
Address areas where unblockable damage is used

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#166]
Places where Unblockable damage is used:
- Wound/Wrack uses Unblockable (but you already knew that).
- Turn/Dispel Undead uses Unblockable.
- As does Ravage Spirit.
- Death touch monster ability uses Unblockable.
- Shockwave uses Unblockable.
- Doom (the item ability) uses Unblockable.
- As does the inverted Major Healing (which didn't exist in legacy).
- And Affect Health items.
- An item that forcibly ends flight can in some situation inflict Unblockable damage.

---
This is an item logged from the To-Do and was originally reported by (@CelticMinstrel?). If you are familiar with or can recreate this bug, please provide details here

**Comment by CelticMinstrel** [comment]
I _think_ this was actually addressed in the end, but I'd have to look again.

**Comment by CelticMinstrel** [comment]
I don't even remember what this was about anymore. Since I thought it was probably addressed back in 2018, I guess I'll close it.
