### ISSUE TITLE
Expand SDF array

### ISSUE THREAD

**Issue by sylae** [calref/cboe#17]
_Original author: celtic.m...@gmail.com (April 26, 2009 02:04:02)_

I think it would be a good idea to expand the Stuff Done Flags array.
Currently, it's 10 wide by 310 high. Expanding it vertically isn't an
option since the last 10 rows are reserved for in-game use, so naturally it
makes sense to expand it horizontally instead. I think that making its
width anywhere from 30 to 100 slots would be good.

Many people use a system whereby stuff done flags related to towns have a
first coordinate which is the number of the town (0 through 199); by adding
more flags like this, we can reduce instances where a town using more than
10 SDFs requires some that would normally be allotted to another town. This
could reduce confusion on the part of the developer (though keeping a
careful record of SDFs used is usually good practice anyway).

_Original issue: http://code.google.com/p/openexile/issues/detail?id=5_

**Comment by CelticMinstrel** [comment]
I'm not sure why this is still open when it was implemented even before the switch to github...
