### ISSUE TITLE
Merge the two start scenario buttons to free space for another button

### ISSUE THREAD

**Issue by CelticMinstrel** [calref/cboe#173]
There's currently one unused button in the main menu, labelled "How to Order". Clicking it currently does nothing. I think it should be replaced with some other button that does something useful, but I'm not sure what that should be.

Also, if the two start scenario options were merged, there would be another free button to which some action could be assigned.

**Comment by x-qq** [comment]
I think this was resolved recently in 7233a8ba780f893474a8449e85fb01ab40af74c0

**Comment by CelticMinstrel** [comment]
Yes, the unused How to Order button has been changed to Preferences.

**Comment by CelticMinstrel** [comment]
The second half of this was implemented in 093be0d99a685f117355c78c786f262ed4da141e. All that's left before it can be closed is to come up with a function for the unused button that was formerly called "Custom Scenario".

One possibility is to make it open the character editor (with the active party, if any), but I'm open to any other ideas.

**Comment by CelticMinstrel** [comment]
Another idea: add an achievement system and use the spare button to open an achievements list.

**Comment by NQNStudios** [comment]
@CelticMinstrel Are you amenable to the tutorial (#174) taking over our extra menu button?

If it did, I think we would want it to come first. So rather than this:

![image](https://github.com/user-attachments/assets/d896ffa6-eefa-47f2-8f45-91b6821a5552)

Maybe like this:

![image](https://github.com/user-attachments/assets/e3449ea2-ce62-43c8-99a6-7af522f903c8)

**Comment by CelticMinstrel** [comment]
I guess this layout makes the most sense to me.

|             |                |
|-------------|----------------|
| Tutorial    | Make New Party |
| Load Game   | Start Scenario |
| Preferences | Credits        |
