### ISSUE TITLE
Get MSTEST integration on Visual Studio projects

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#177]
To be honest, i'm not sure how the tests are being executed on windows right now.
Goal will be to get MSTEST integration w/o affecting tests for other platforms.

**Comment by CelticMinstrel** [comment]
Currently the tests are executed on Windows by simply running the test project.

**Comment by NQNStudios** [comment]
This seems a bit frivolous to me.

**Comment by CelticMinstrel** [comment]
The unit tests _work_ on Windows, so that's good enough for me.
