### ISSUE TITLE
Store custom item graphics along with a savegame

### ISSUE THREAD

**Issue by sylae** [calref/cboe#18]
_Original author: celtic.m...@gmail.com (April 26, 2009 02:39:37)_

Currently when leaving a scenario, any items with custom graphics are
removed. I think it would be far better to, when leaving the scenario, copy
these graphics to a new graphics sheet which is saved along with the party,
most likely as a PNG file with the same name as the savefile. To support
this, the party record would need to keep track of which graphics in its
sheet are used and which are not, so that it can copy graphics into an
unused (not necessarily empty) slot as necessary.

_Original issue: http://code.google.com/p/openexile/issues/detail?id=6_

**Comment by CelticMinstrel** [comment]
Implemented, might need some quirks ironed out though.

**Comment by CelticMinstrel** [comment]
Since it's clearly implemented (plus at least some of the quirks and bugs have been fixed), I'm closing this. If there are indeed further quirks to be ironed out, they can be opened as new issues.
