### ISSUE TITLE
Update SConstruct to support target selection

### ISSUE THREAD

**Issue by CelticMinstrel** [calref/cboe#187]
Currently, running `scons` builds _everything_ - the game, the editors, the tests, and (on Mac and Windows) a distribution package. That is, to say the least, a bit excessive. It would be better if you could select the target to build on the command-line, for example `scons game` builds only the game, `scons pcedit` builds only the character editor, `scons tests` builds and runs the tests, `scons package` builds a distribution package, etc. We could also in principle add `scons install` which actually installs the app to standard locations on your operating system (for example, on the Mac, copying it to _/Applications_ or _~/Applications_).

**Comment by clort81** [comment]
SConstruct also breaks with python 3.x.  Needs 2.x.
scons can be forced to use python2 by editing the first line of /usr/bin/scons.

**Comment by madwizard** [comment]
It's quite easy to move SConstruct to python3, question is, how will CI react to that?

**Comment by CelticMinstrel** [comment]
Turns out I created this issue twice – it's a duplicate of #52.
