### ISSUE TITLE
Have animations be 'animated' in the scenario editor

### ISSUE THREAD

**Issue by sylae** [calref/cboe#19]
_Original author: sylaecorell (May 02, 2009 13:59:14)_

<b>What steps will reproduce the problem?</b>
1. Using the scenario editor.

<b>What is the expected output? What do you see instead?</b>
- Well, It might be better if animations were actually animated when editing 
them (in the map view, but it'd probably be good if they were shwn in the 
terrain editing window too). Currently, I just see the first frame of the 
image.

<b>What version of the product are you using? On what operating system?</b>
- Ormus' last working release on Windows, but I'm pretty sure all the other 
versions do it too.

_Original issue: http://code.google.com/p/openexile/issues/detail?id=9_

**Comment by CelticMinstrel** [comment]
Implemented, but currently only in dialogs, not in the map editor.

**Comment by CelticMinstrel** [comment]
I'm going to close this issue. If someone wants animations in the map editor as well, they can start a new issue.
