### ISSUE TITLE
Menu bar doesn't show on Linux

### ISSUE THREAD

**Issue by jkatzmewing** [calref/cboe#195]
As per title. No menu bar in BoE, CharEd, or ScenEd, so e.g. interacting with preferences is not possible.

(Ubuntu 19.04 x86-64, g++ 8.3.0, built with scons)

**Comment by CelticMinstrel** [comment]
This is a known bug which I haven't addressed largely because I'm not sure how best to implement a menu in Linux - if you happened to have any suggestions, I'd really like to hear them!

**Comment by jkatzmewing** [comment]
Oh! I hadn't realized that SFML didn't include any kind of menu widgets. Whoops.

I'm pretty inexperienced in GUI/widget related stuff myself, but may see if I can throw something together. My first thought honestly is to get rid of the menus, and move the menu-only functionality to an extra row of buttons or such.

**Comment by CelticMinstrel** [comment]
SFML is not a GUI toolkit, it's just a graphics toolkit - similar to SDL. So, it doesn't provide any widgets whatsoever.

That means that I have to do one of the following:

1. Re-implement a menubar from scratch using just SDL. The custom GUI framework already in BoE _might_ have some use here, not sure.
2. Find an external toolkit that does (ideally) nothing but menus, preferably based on OpenGL.
3. Figure out a way to substitute the menus with something using Zenity (for Linux users only of course).
4. (insert solution here)

**Comment by CelticMinstrel** [comment]
Implemented in the linked issues plus 1d61d48ec3e0cdb0155a434072c1dfdab9502686 5675ab8c71666a5cd903d64f5442ac9053cd796f c4c201db6ee3fa073cfa8732846408e8851a687b
