### ISSUE TITLE
City disappeared after loading a saved game

### ISSUE THREAD

**Issue by jeremeriluoto** [calref/cboe#197]
In valley of dying things -scenario the starting city disappeared after loading a game and returning to the location of the city.
[blades-of-exile-team-save.zip](https://github.com/calref/cboe/files/4008389/blades-of-exile-team-save.zip)

**Comment by CelticMinstrel** [comment]
By disappeared, you mean it's not even on the map?

**Comment by jeremeriluoto** [comment]
Yes, the town completely vanished from map. Now that I tried to load again, it reappeared.

**Comment by clort81** [comment]
Fixed now! \o/  Thanks CM!!!

**Comment by CelticMinstrel** [comment]
The actual fix was 479cfb75f6ee2bfe8b11f846f257cdff6495defb for the record.
