### ISSUE TITLE
Special steps showing up in console

### ISSUE THREAD

**Issue by jeremeriluoto** [calref/cboe#198]
When nearing and encounter or special node the console is filled with "steps". While outdoors, the encounter node have to be stepped in multiple times before the actual encounter starts.

![issue_steps](https://user-images.githubusercontent.com/38283395/71560732-50e65000-2a76-11ea-8357-8f9a98ebb8e8.JPG)

**Comment by CelticMinstrel** [comment]
This means that encounter step mode is enabled, which waits for a keypress in between each special node that gets executed. So this is likely closely related to #200 - although encounter step mode is a separate flag from debug mode, they could both be suffering from the same problem.

**Comment by CelticMinstrel** [comment]
I think this is basically the same issue as #200, just affecting a different variable.
