### ISSUE TITLE
Highlight clickable words in talk mode

### ISSUE THREAD

**Issue by sylae** [calref/cboe#20]
_Original author: celtic.m...@gmail.com (May 22, 2009 21:52:30)_

When in talk mode, you currently guess at which words the person may
respond to. It would be nice if those words were instead highlighted so
that you can easily see what they are.

_Original issue: http://code.google.com/p/openexile/issues/detail?id=10_

**Comment by CelticMinstrel** [comment]
Implemented (works pretty much the same as original Nethergate).
