### ISSUE TITLE
Abort game -> load game -> Loading Blades of Exile save file failed.

### ISSUE THREAD

**Issue by jeremeriluoto** [calref/cboe#201]
When starting a new game or loading a game and aborting back to main menu doesn't let you load your game any more. Only error message is displayed: "Loading Blades of Exile save file failed.". You have to restart the game to be able to load again.

**Comment by x-qq** [comment]
Cannot reproduce on current master on linux.

**Comment by CelticMinstrel** [comment]
I'm not sure about this exact case, but there are definitely still some circumstances where a "loading save failed" or "loading scenario failed" message is nonsensically displayed. Some relate to cancelling things.

**Comment by wrldwzrd89** [comment]
In my own games I've run into similar issues. The fix was always the same: Handle NO_CHOSEN differently from DIALOG_CLOSED or CANCEL_CHOSEN.

**Comment by NQNStudios** [comment]
If the OP was running on Windows, I wonder if this could be the same error as #368

**Comment by NQNStudios** [comment]
I can't reproduce this on Mac or Windows. @CelticMinstrel maybe we can close it?
