### ISSUE TITLE
Firing arrows change skin on some occasions

### ISSUE THREAD

**Issue by jeremeriluoto** [calref/cboe#202]
On some encounters when firing missiles the missile skin is dark line with yellow head. On same encounter the skin can change to dark line with poisonous green head, although poison was not applied or used.

**Comment by clort81** [comment]
![greenarrow](https://user-images.githubusercontent.com/51511737/71761464-1db71d00-2ecb-11ea-949b-1577d8bb991b.png)

Confirmed on my linux build.

**Comment by clort81** [comment]
I noticed that arrows bought in (another?) store displayed the correct arrow graphic.

**Comment by CelticMinstrel** [comment]
We discussed this on IRC, and I believe the issue is simply that starter arrows don't specify the correct missile graphic.

(To clarify, "starter arrows" are the arrows given to a new character under certain conditions, which are hard-coded.)

**Comment by CelticMinstrel** [comment]
So, looking at the code (line 170 of item.cpp), it seems that my guess was wrong? It _is_ correctly setting the missile graphic for the starter items.

So, new theory. Given that you mention it doesn't happen on a fresh party, it could be a matter of not storing the missile graphic in the saved game.
