### ISSUE TITLE
Shop Items not showing description when clicking on Info graphic.

### ISSUE THREAD

**Issue by clort81** [calref/cboe#210]
Shop Items not showing description when clicking on Info graphic.

![shop_nodescription](https://user-images.githubusercontent.com/51511737/71760372-e6da0a80-2ebc-11ea-941d-3cbcaf565217.png)

Windows version, for comparison.
![shop-correctiteminfo3](https://user-images.githubusercontent.com/51511737/71760573-19d1cd80-2ec0-11ea-9d97-d4fbde29b777.png)

**Comment by clort81** [comment]
Confusing, now i get item info.  Cannot reproduce :/

**Comment by CelticMinstrel** [comment]
The empty space is reserved for a scrollbar when present, but clicking that empty space shouldn't actually do anything… so that might be a bug.

It'd also be nice to push the buttons right when the scrollbar is invisible, but… that would probably break things.

**Comment by clort81** [comment]
I don't think this can be called a bug.   Closing.
