### ISSUE TITLE
Magic Barrier tiles not animated.

### ISSUE THREAD

**Issue by clort81** [calref/cboe#214]
In the WinDOS version, the Magic Barrier tiles are animated but not in openboe (my build).

![magicbarriernotanimn](https://user-images.githubusercontent.com/51511737/71764791-9c708200-2eec-11ea-9b58-6d5a63c9189f.png)
Savegame outside Marralis.
[clorsave03_animatedbarrier.zip](https://github.com/calref/cboe/files/4021836/clorsave03_animatedbarrier.zip)

**Comment by x-qq** [comment]
Confirmed on Debian GNU/Linux amd64 on 479cfb75.

**Comment by clort81** [comment]
I found that forcefields in the Magician's School in Hall of Audience are animated.  Savegame attached.
