### ISSUE TITLE
Curing Poison doesn't update Party stats to reflect cure.

### ISSUE THREAD

**Issue by clort81** [calref/cboe#215]
Curing Poison doesn't update Party stats to reflect cure.

![curing_poison_not_update](https://user-images.githubusercontent.com/51511737/71765213-e6a83200-2ef1-11ea-8a30-0438cd5197ae.png)

However in the Fungal Cavern, Cure Poison updates the Party stats:
![curingpoison](https://user-images.githubusercontent.com/51511737/71765430-f2e1be80-2ef4-11ea-8a74-905b7912252b.png)

**Comment by CelticMinstrel** [comment]
Hmm, did the poison change from a red P to a black P when you cured it, or did it just not update at all? There are two "levels" of poison, and it _might_ be that curing the higher level just reduces it to the lower level...

**Comment by x-qq** [comment]
Confirmed, no update happens when curing 'green' poison on world map.

**Comment by CelticMinstrel** [comment]
So basically, it works in towns/dungeons but not outdoors?

**Comment by x-qq** [comment]
I have tested it in town with the same result - out of combat a green poison is cured but party status is updated to reflect that only after a move.

**Comment by CelticMinstrel** [comment]
Fixed in 29ef8b9c1eb591c0208be6d5141957a18fee0806
