### ISSUE TITLE
Keys 1, 2, 3, 4, 5, 6 should switch active character in the party but only 1, 2 and 6 work

### ISSUE THREAD

**Issue by x-qq** [calref/cboe#217]
Tested on 64bit linux.

Additionally, it was reported on IRC that on Windows, key "5" also works (but 3 and 4 still don't).

**Comment by clort81** [comment]
Confirmed on aarch64.

**Comment by clort81** [comment]
The keyboard event handler simulates a mouseclick over the Party Stats window to switch characters.

In game/boe.actions.cpp: ~1726, increasing offsets into the box works for me
```
// Clort the pass points needed to be shifted further into the party stat box, for some reason +20,4 worksforme
                case '1': case '2': case '3': case '4': case '5': case '6':
                        pass_point = pc_buttons[((short) chr) - 49][PCBTN_NAME].topLeft();
                        pass_point.x += 20 + win_to_rects[WINRECT_PCSTATS].left;
                        pass_point.y += 4 + win_to_rects[WINRECT_PCSTATS].top;
```

**Comment by wrldwzrd89** [comment]
Could anything be altering the width of the PC status area, causing the simulated clicks to go to the wrong place? For instance, a status effect changes the name of your character in such a way as to cause the status line to wrap?

**Comment by CelticMinstrel** [comment]
Pretty sure the status line does not wrap… it would be cut off if there are too many, I believe.
