### ISSUE TITLE
No Party Stats update after drinking from river.  (possibly duplicate)

### ISSUE THREAD

**Issue by clort81** [calref/cboe#221]
No Party Stats update after drinking from river.  (possibly duplicate)

Pretty sure this isn't system-specific.  See screenshot.  Status update occurs after next move on game map.

![bug-nostatuseffects_update](https://user-images.githubusercontent.com/51511737/71822289-cfee1080-3094-11ea-9827-4b155c999895.png)

**Comment by CelticMinstrel** [comment]
Fixed in 29ef8b9c1eb591c0208be6d5141957a18fee0806
