### ISSUE TITLE
Moving one space diagonally sometimes moves character two spaces.

### ISSUE THREAD

**Issue by clort81** [calref/cboe#225]
In combat, i try to move a character one space diagonally down-left by quickly hitting down-left.

In some situations, it moves the character two diagonal spaces.  This seems to be a bug to me (cannot reproduce in original game).

In another instance, hitting up-left to attack an enemy diagonally resulted in my next character moving left (into a force field and taking damage).

Somehow the 'diagonal combos' seem to be not clearing input buffer after one 'get'.

**Comment by CelticMinstrel** [comment]
For the record, the official way to move is to use the numeric keypad, where diagonal movement is on separate keys. The double-key diagonal movement may be a bit of a hack to allow laptops to play without using the FN key.
