### ISSUE TITLE
Item Descriptions

### ISSUE THREAD

**Issue by sylae** [calref/cboe#23]
_Original author: icelizar...@gmail.com (January 21, 2011 08:21:58)_

The ability to make (and view, of course) text descriptions for items, a la Realmz or the earlier Exile games. --Sugg. by TheLostOne 

_Original issue: http://code.google.com/p/openexile/issues/detail?id=27_

**Comment by CelticMinstrel** [comment]
Implemented and working, though the bladbase still has no descriptions on its items.

**Comment by CelticMinstrel** [comment]
Since I've now merged ADoS's descriptions into the Blades of Exile Base (and the preset scenarios), this can now be considered complete.
