### ISSUE TITLE
Multitarget spells don't tell you how many targets you have

### ISSUE THREAD

**Issue by clort81** [calref/cboe#236]
Mage spell Weak Summoning (perhaps others too) sometimes shows a red targeting reticle, which can be clicked on/off, but never summons a monster.

Sometimes it does work, summoning a monster, but then does not show the red targeting reticle at all.   Oh, i see it indicates that two monsters can be summoned.

USER NEEDS TO CLICK ON ONE TILE, THEN ANOTHER to invoke the spell.
(this could be instructed in console)

Here is a screenshot of the failing mode:
![boe-bug-summoning](https://user-images.githubusercontent.com/51511737/72669019-1ba5a000-3a2d-11ea-9dd1-e60af74a2680.png)

**Comment by CelticMinstrel** [comment]
I get the impression that something is still wrong in that screenshot, but not quite sure… should the number of targets be shown somewhere?

**Comment by CelticMinstrel** [comment]
Okay, so it does mention "hit space to cast" in the console, which would work to cast the spell without selecting the maximum number of targets (though I wouldn't want to do that with a summoning spell). But nowhere does it mention how many targets you have. Need to check whether the original game provided this information.

**Comment by wrldwzrd89** [comment]
My memory suggests that the only indication of targets was the presence / absence of a targeting reticle after adding / removing a target... does the original BoE work in Wine?

**Comment by CelticMinstrel** [comment]
I don't think the original BoE works on WINE. I can run it in DOSBox though (Win3.1), and I can also run the original Mac BoE in Basilisk II. So I can check myself at some point.

**Comment by clort81** [comment]
It works for me now!  Closing for issue-hygiene!
