### ISSUE TITLE
Non-stop disk access from Resource Manager

### ISSUE THREAD

**Issue by x-qq** [calref/cboe#241]
Openboe keeps accessing the filesystem constantly, calling stat() on various resource paths (fonts, images, etc).

It is caused by the fact that in resource manager's get() function there simply isn't a branch that would **not** lead to disk access (provide the resource purely from cache). 

https://github.com/calref/cboe/blob/master/src/fileio/resmgr/resmgr.hpp#L146

**Comment by wrldwzrd89** [comment]
Perhaps BoE needs a resource cache, then - preferably one that has eviction, so as not to use more RAM than needed.

**Comment by clort81** [comment]
Why add a cache to code that doesn't need to be called in the first place?

OO -'thinking' strikes again?

**Comment by CelticMinstrel** [comment]
Fixed in 542c037342809f8a96f0066865a381d9e1fb5b4d b0fddcd8a67db5111dda14606431271a5de958bc 2d1ee24473b75896c2c213776b8e67620ce91763
