### ISSUE TITLE
Help index page not found

### ISSUE THREAD

**Issue by x-qq** [calref/cboe#242]
Currently "Help -> Index" in menu leads to https://blades.calref.net/doc/game/Contents.html which is 404.

**Comment by CelticMinstrel** [comment]
For the record, if local docs exist it'll use those in preference to the web docs, but I'll update the URL.

**Comment by x-qq** [comment]
This will not work either because the directory it looks for is doc/ while under build directotry there is **docs/**

**Comment by CelticMinstrel** [comment]
That's easily fixed?

**Comment by wrldwzrd89** [comment]
Are the local docs always generated with the build? If so, relying on a local copy is easier. This only makes sense if building the docs doesn't have optional dependencies the standard build process doesn't require or check for.

**Comment by CelticMinstrel** [comment]
They're not generated with the build, they're simply in the repository, no generation required. The test builds I've been making don't include the docs, which is the main reason to have the web version as an option, but perhaps we could add other possible search paths for a local copy such that anyone running from source will automatically use the local copy. (That would need separate logic for scons builds, Xcode builds, and Visual Studio builds. Possibly also separate Mac vs non-Mac logic even in the scons case. Or, perhaps the easiest way would be to just encode a secondary search path as a preprocessor directive.)

**Comment by x-qq** [comment]
Same problem in scenario editor.

**Comment by x-qq** [comment]
Same problem in character editor.

**Comment by CelticMinstrel** [comment]
Fixed in 91da0ed4d0ef4e85068936ab3340cdf29ced1fb9

**Comment by CelticMinstrel** [comment]
Fixed in 91da0ed4d0ef4e85068936ab3340cdf29ced1fb9
