### ISSUE TITLE
Blinlock: Reward for clearing mines not received.

### ISSUE THREAD

**Issue by clort81** [calref/cboe#254]
Cleared the mines in Blinlock.  Mayor claims reward is awarded, but nothing appears in inventory or shows-up on game-world view.  

Tried with main character unencumbered (dropped armor first) but still no broadsword received.  Is this a bug?

Savefile attached.
[blinlock_reward.exg.gz](https://github.com/calref/cboe/files/4164320/blinlock_reward.exg.gz)

**Comment by CelticMinstrel** [comment]
So just to clarify: you asked about iether "task" or "reward", and he responds something like "good news the spirit is dead" but you don't get a sword?

The reward should be a normal steel broadsword (which might show up as just an unidentified broadsword). If every pack was full (24 items), you would miss it, but it should still give even if it would put you over the weight limit, as long as there's space.

I'm pretty sure the log should say who exactly received the item; if it doesn't, then no-one did, probably. However, if that happened, asking him about "reward" should produce the same response and thus give another chance at the item.

**Comment by x-qq** [comment]
Can reproduce on current master.

**Comment by clort81** [comment]
Yes i asked about the reward and he claims to give it to me. 

ADos seemed to confirm a different reward not given in another game.  He also said my savefile resulted in town empty of characters. If i understood correctly.

**Comment by CelticMinstrel** [comment]
Your savefile doesn't appear to contain the data that would result in an empty town, so I suspect ADoS may have been loading it with an older, more broken build. (I do see one value that looks suspiciously wrong in party.txt though - SHOPSTOCK is set to MAX_INT for some reason.)

**Comment by NQNStudios** [comment]
A similar bug happened to me while playing "On a ship to Algiers". I opened the scenario in the editor and tracked down the node that isn't working. It's a "One-Time Give Item" node. Then I opened valleydy in the editor to compare, and found it is the same node type. Now I'll look into the code to see where it's going wrong and fix.

If possible, I will also contribute a unit test for this.
