### ISSUE TITLE
Requested Graphics submission Thread

### ISSUE THREAD

**Issue by clort81** [calref/cboe#262]
Crystal Dude Light halo remake:
![Clort-CrystalDudeAttack](https://user-images.githubusercontent.com/51511737/74307239-2cfc7680-4d65-11ea-8807-f4cf234ab191.png)
(sorry for misunderstanding first time)
![CrystalDudeAttack-Final](https://user-images.githubusercontent.com/51511737/74307770-a8aaf300-4d66-11ea-91e2-0cc5022632ad.png)

**Comment by clort81** [comment]
![CystalDude-Fixed2](https://user-images.githubusercontent.com/51511737/74338907-550aca80-4da3-11ea-8351-41fa1f03eb53.png)

Changes for ADoS.

**Comment by clort81** [comment]
### Leather Helm 

![leatherhelm3](https://user-images.githubusercontent.com/51511737/74409588-5c7bb380-4e37-11ea-8b90-f7d5ab02bae7.png)

13x13 is really challenging

**Comment by wrldwzrd89** [comment]
The size these are limited to sure doesn’t help.

**Comment by clort81** [comment]
ADoS made some cool buttons with more visible LEDs.  Here's an idea with darkened text for inaccessible spells - easier to identify with eyes what's unavaiable to cast, imo.

![darkenedspells](https://user-images.githubusercontent.com/51511737/74485483-2718a980-4ebb-11ea-9cdf-0e05fc5e86b1.png)

Testing pic has dark grey instead of pure black for inactive buttons.

**Comment by CelticMinstrel** [comment]
Leather helmet: Looks great! I'll look into adding it to tinyobj soon™.

Larger LED: Not a fan of this to be honest... I'm not quite sure why. Something about how the LED takes up so much of the button, I guess? I won't deny that the default LEDs are a bit suboptimal though...
