### ISSUE TITLE
Add pushable stone block and forcecage

### ISSUE THREAD

**Issue by sylae** [calref/cboe#27]
_Original author: celtic.m...@gmail.com (May 23, 2009 02:54:29)_

<b>Enter a description of the new feature you would like to see.</b>
I'd like to see a pushable stone block &quot;field&quot; and a forcecage &quot;field&quot;. I
have graphics for these already.

The stone block would be almost the same as the crate, but when move off of
a conveyor and land on it the block would not be smashed. (Possibly you
could be damaged.) Also it would not be a container.

The forcecage would simply prevent anything occupying the same space from
moving off of that space. This includes items, creatures, and party members
moving along a conveyor belt. If occupied by a creature or party member,
there should be a chance each turn for the forcecage to break, possibly
using similar criteria as that used for breaking barriers. It could also be
removed by Dispel Barrier spells and items.

_Original issue: http://code.google.com/p/openexile/issues/detail?id=15_

**Comment by CelticMinstrel** [comment]
Implemented and working.
