### ISSUE TITLE
Required attributes missing on elements in multiple dialog xml files

### ISSUE THREAD

**Issue by seisatsu** [calref/cboe#273]
In the following xml files, the element "led" does not have the required attribute "width", which will likely lead to a crash when they are loaded. This has been confirmed with tip-of-the-day.xml and pc-alchemy-info.xml.
* edit-item-shortcut.xml
* edit-outdoor-encounter.xml
* edit-special-item.xml
* edit-town-details.xml
* edit-townperson.xml
* graphic-types.xml
* make-scenario1.xml
* make-scenario2.xml
* new-town.xml
* pc-alchemy-info.xml
* pc-spell-info.xml
* tip-of-day.xml

In addition, edit-party.xml throws `Required attribute anchor missing on element button (file edit-party.xml, line 4, column 5)`. This can be fixed by changing the "relative" attribute from "neg pos" to "neg abs".

I will continue appending to this issue as errors occur, while applying temporary fixes to my own files. (I do not know the appropriate widths for the led elements, but having something there will at least allow the game to continue on my end until fixes are pushed.)

**Comment by CelticMinstrel** [comment]
I believe any width should fix the led elements, if it's less than 14 or so (the actual width of the button) it'll be expanded to that size.

I'm guessing a lot of these are older LEDs that haven't been updated to contain their label.

**Comment by NQNStudios** [comment]
A crash in the scenario editor when I click Edit Town Details is preventing me from diagnosing a different bug, so I think I'll try to fix this.

It most be because `edit-town-details.xml` is on that list, because the missing attribute 'width' message is the one I'm getting.

**Comment by CelticMinstrel** [comment]
Generally speaking, the appropriate width is "wide enough that the full label can fit" and also usually "same width as other LEDs in the same column".

**Comment by CelticMinstrel** [comment]
By the way, you might want to check out #274 before getting started on this

**Comment by CelticMinstrel** [comment]
I think this should be considered fixed by b03a200f8a54ff68bb79e8778c004dcb880d887d and c3dd886783c3fea2fb0f95c228e74b1b79827b5c?

**Comment by NQNStudios** [comment]
With #298 in place, I agree.
