### ISSUE TITLE
I can walk through walls

### ISSUE THREAD

**Issue by dh337071** [calref/cboe#278]
I can walk through walls. I have the most recent version for windows from http://pentalithia.ca/oboe/?C=M;O=D.

BoE-Win-a8e120d.zip

**Comment by CelticMinstrel** [comment]
I think that's fixed in latest master. The bug is that there's a debugging mode that lets you walk through walls which sometimes gets turned on when it shouldn't be. Whenever it happens, pressing Shift+D should fix it.

**Comment by NQNStudios** [comment]
I feel like this can be closed, if it was a known issue and fixed.

**Comment by CelticMinstrel** [comment]
I think the commit that fixed it was d314432664bb16c1804bed574a7c0dd22e9c2923.
