### ISSUE TITLE
include <istream> and <ostream>  in spell.hpp to enable compile

### ISSUE THREAD

**Issue by clort81** [calref/cboe#280]
from conversation in IRC, include <istream> and <ostream> in spell.hpp to enable compile on linux

**Comment by CelticMinstrel** [comment]
I think `<iosfwd>` should be sufficient instead of `<istream>` and `<ostream>`, does that work?

**Comment by NQNStudios** [comment]
I can compile on Linux (Arch). Was this fixed? If we can get Linux CI working, I think we can close this.

**Comment by CelticMinstrel** [comment]
Linux CI _is_ now working so yeah, I guess there's no reason for it to stay open.
