### ISSUE TITLE
Patch for /trunk/Win32/Blades of Exile/boe.specials.cpp

### ISSUE THREAD

**Issue by sylae** [calref/cboe#30]
_Original author: m...@finishingpost.tv (July 18, 2012 16:24:41)_

Fixed bug in special node type 181 (SPEC_TOWN_PLACE_MONST) so that ex2b sets whether to force the placement, rather than ex2a.

_Original issue: http://code.google.com/p/openexile/issues/detail?id=30_

**Comment by CelticMinstrel** [comment]
Closing this, since it relates to the frozen Classic Win32 codebase.
