### ISSUE TITLE
Clicking "Cancel" in Zenity file-picker on Linux causes core dump.

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#301]
On Linux, if you click "Cancel" from a file picker dialog, you get a crash with a core dump (In the game, and both editors)

It's because here:
https://github.com/calref/cboe/blob/master/src/tools/winutil.linux.cpp#L134

There is no handling for a popen() that doesn't result in success.

I think I can fix this.

A related problem is that the Zenity picker doesn't let you choose a file that doesn't exist yet, so creating a new scenario in the editor is impossible (maybe you could do it by picking a file that DOES exist an overwriting it, but... that would be bad...)

**Comment by NQNStudios** [comment]
It looks like the API for Windows also expects to return a string no matter what, and doesn't handle for a Cancel. This could definitely explain #268

**Comment by CelticMinstrel** [comment]
> A related problem is that the Zenity picker doesn't let you choose a file that doesn't exist yet, so creating a new scenario in the editor is impossible (maybe you could do it by picking a file that DOES exist an overwriting it, but... that would be bad...

Was this fixed or does it need to be split to a new issue?

**Comment by NQNStudios** [comment]
Looks like not fixed. I'll open a new issue
