### ISSUE TITLE
In a healer's shop, clicking a dead character's name causes segfault

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#304]
(on linux)

**Comment by NQNStudios** [comment]
Actually, this might be more complicated. Clicking anywhere on the screen other than "Done" is causing a segfault. And sometimes, the "Done" button is too (but that might be a hitbox thing).

**Comment by NQNStudios** [comment]
It only happens when the initially active character doesn't need healing.

**Comment by CelticMinstrel** [comment]
I might've spotted a commit in #285 that's related to this…

**Comment by fosnola** [comment]
I just did some tests with my last version of cboe ( monster code branch ), I could not reproduce this problem ( and asan did not detect anything ) with two dead characters and when any character need healing. 

I don't remember seeing this problem, but I guess it was probably fixed by side effect when I fixed all the problems asan was finding :-~ 

**Note** or this may be related to https://github.com/fosnola/cboe/commit/52ebc7060cc64b386b24c8c228082c6c9fc3a843

**Comment by fosnola** [comment]
I recompiled cboe/master, asan reports a first error in handle_shop_event[boe.dlgutil.cpp] that is corrected in https://github.com/fosnola/cboe/commit/72e1268d0b495204b582bf41eed14a42626e7da4

**Comment by CelticMinstrel** [comment]
Okay, I fixed that buffer overrun. Is the crash fixed now, or is it more likely to be fixed by 52ebc70?

**Comment by fosnola** [comment]
I was thinking more of the second patch of https://github.com/fosnola/cboe/commit/52ebc7060cc64b386b24c8c228082c6c9fc3a843 
```
@@ -219,6 +219,9 @@ void handle_shop_event(location p) {
 	}

 	for(short i = 0; i < 8; i++) {
 		// asan: 
 		if (i + shop_sbar->getPosition()>=shop_array.size())
 			break;
 		unsigned long what_picked = shop_array[i + shop_sbar->getPosition()];
 		if(what_picked >= active_shop.size()) break;
 		if(active_shop.getItem(what_picked).type == eShopItemType::EMPTY)
```
But then, asan stops by default at the first problem found, there may be others after...

**Comment by CelticMinstrel** [comment]
I don't see that code in the linked commit?

**Comment by fosnola** [comment]
Oops, I meant https://github.com/fosnola/cboe/commit/72e1268d0b495204b582bf41eed14a42626e7da4 (i.e. when I copy and paste the link, I choose the wrong one).

**Comment by CelticMinstrel** [comment]
Ah, I got it. That does look like it could be related. (But there was also something in the other commit that looked possibly relevant.)

**Comment by NQNStudios** [comment]
This is fixed on master.
