### ISSUE TITLE
Opening a party in Character Editor fully heals and overwrites

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#311]
On Linux. I'm trying to make a party to test #304 and discovered a different problem....

When I save in a scenario with character(s) dead, in a town, then open that file in the character editor, the characters are raised from the dead and fully healed. And the file is overwritten, even without clicking to save.

**Comment by NQNStudios** [comment]
Well, when I remembered this bug, I was completely convinced it was caused by the same problem as #324 and would be fixed by #328, too.

My testing on Windows and Linux shows that you can now open a party in the character editor without healing them when you load the file again in-game. Which was the original problem (or so I thought--if it was connected to #324 it's more likely that loading a party in any way at all would fully heal them without actually overwriting the file, and I was just blaming the character editor).

BUT.

Now, on Windows, in the character editor, the PCs health *shows* as at maximum, even when it's not. Maybe a different bug entirely. But I think the specific bug I described here has been fixed by #328

**Comment by CelticMinstrel** [comment]
> Now, on Windows, in the character editor, the PCs health _shows_ as at maximum, even when it's not. (On Linux the correct values show.) Maybe a different bug entirely. But I think the specific bug I described here has been fixed by #328

Is this still an issue? If so, was a new issue opened about it?

**Comment by NQNStudios** [comment]
No, I've just checked and it's not.
