### ISSUE TITLE
Linux PC editor build is missing a way to add items

### ISSUE THREAD

**Issue by CelticMinstrel** [calref/cboe#313]
Mac and Windows have an Add Item option in the Party menu. Linux does not. See the rc file for reference.

**Comment by NQNStudios** [comment]
I'm seeing that the menu item *is* there, and it works--until I close the editor and open the save again, either in the game or in a restarted instance of the character editor.

**Comment by NQNStudios** [comment]
Any time I load a party, I'm seeing that the inventory is wiped.

**Comment by CelticMinstrel** [comment]
Hmm, so I was wrong? I looked at the pc.menu.cpp file and thought it was missing, but I must've glossed over it somehow, because now when I look it's clearly there. Not sure how I missed it. It was added in 7e73a21f5c48dada7a5fd19eb8f3747e261c3a56.

You can open another issue for the inventory wipe. It's probably caused by my recent save file refactoring?
