### ISSUE TITLE
Clickable widgets placed inside a stack must be clicked twice to trigger them

### ISSUE THREAD

**Issue by CelticMinstrel** [calref/cboe#314]
This can be seen in the Choose Scenario dialog, which uses clickable text widgets.

Might be related to #133

**Comment by NQNStudios** [comment]
Actually, you can also click widgets in a stack once, then click any other widget, and the first widget will be triggered.

i.e. Click Start Scenario -> Click VoDT -> Click Cancel, and it will launch VoDT.

**Comment by NQNStudios** [comment]
This makes no sense... in the debugger, control flow simply skips out of a function before it's complete.
