### ISSUE TITLE
Allow cancelling any action by pressing Escape

### ISSUE THREAD

**Issue by CelticMinstrel** [calref/cboe#322]
Most actions can be cancelled by pressing the same key again, but it would be useful to have a more general way of cancelling an action.

This should probably wait for #319.

**Comment by NQNStudios** [comment]
I thought that implementing the replay system would invite/inspire opportunities to decouple things and achieve #319. But it really didn't--things are still tightly coupled, and decoupling them remains very daunting and error-prone. I think we should just implement this issue in the current system.
