### ISSUE TITLE
Open Preferences: crash.

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#331]
![image](https://user-images.githubusercontent.com/2584745/215305174-266bbaf2-31b5-4be9-aac3-5d78bbd0e44e.png)

On Windows. In the main menu, or in a scenario, the menubar's File -> Preferences button causes this message and a crash.

**Comment by CelticMinstrel** [comment]
We really need a system to improve error messages in this sort of case. If the dialog said "Failed to cast cButton to cLed" for example, it would be easier to track down the location that raised the error.

I have a feeling that's not readily doable in the current model though. We'd need to convert every dialog into a class like cStringChoice and the like…

**Comment by NQNStudios** [comment]
I think this was caused by having an outdated data folder installed. The game was loading bad xml files from there instead of the repository.
