### ISSUE TITLE
Windows: Custom scenarios hidden in cChooseScenario dialog

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#335]
I did a bunch of debugging to figure out why.

https://github.com/calref/cboe/blob/ca816995ba9da539ed08a568616fbf36bea8bde0/src/game/boe.dlgutil.cpp#L1559

Here, the number of scenario headers loaded is checked for >= 3, which makes sense, BUT the vector being checked only contains custom scenarios, not built-in scenarios. So unless the player has 4 custom scenarios installed, they won't be able to launch custom scenarios.

**Comment by NQNStudios** [comment]
I wanted to check if this is just a Windows thing, and it does affect Linux too. Does Mac also separate custom and built-in scenarios out of this vector?

**Comment by CelticMinstrel** [comment]
> Does Mac also separate custom and built-in scenarios out of this vector?

Huh? Is this platform-specific code? Most things are the same on all platforms, other than winutil and a couple of others…

**Comment by NQNStudios** [comment]
It's not platform-specific, other tan the `extern scenDir` variable --on Windows it's in AppData, on Linux it's in HOME/.config, and on Mac I don't know where it is. I don't think it would do this, but if the installation process on Mac puts built-in scenarios in there it would change the vector's contents.

**Comment by CelticMinstrel** [comment]
No, built-in scenarios in the Mac version go in `Blades of Exile Scenarios/` next to the .app while installed scenarios go in `~/Library/Application Support/Blades of Exile/Scenarios/`. I'm pretty sure this is almost identical in spirit to the situations on Windows and Linux too.

**Comment by NQNStudios** [comment]
The PR should be good across platforms, then. I tested Windows and Linux.
