### ISSUE TITLE
Scenario editor: edit creature: XML parse error

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#342]
I click to edit a creature and get this:

![imagen](https://user-images.githubusercontent.com/2584745/216506460-04115434-d04f-481b-91c6-3f870921d4c8.png)

I thought LEDs didn't require width attribute anymore?

**Comment by NQNStudios** [comment]
also thought that the new dialogs unit test would catch this.

**Comment by CelticMinstrel** [comment]
LED requires a width if it has content. All the previously-recorded cases of this error were an LED without content. I assume this one _does_ have content.

**Comment by NQNStudios** [comment]
The led in question does have content... but it also has a width! https://github.com/calref/cboe/blob/1bc7524ec218782ee469b2cb853f570a3f4eedcc/rsrc/dialogs/edit-townperson.xml#L24

Makes me think I have an outdated file somewhere??

**Comment by NQNStudios** [comment]
It's loading from APPDATA/Roaming/Blades of Exile/data which was outdated.
