### ISSUE TITLE
Dialog scale option

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#350]
I can scale the UI and the map, but not the popup dialogs. On a modern screen, that text is pretty small/eye-straining.

**Comment by CelticMinstrel** [comment]
Probably the main UI scale should just be applied to dialogs too.

**Comment by NQNStudios** [comment]
Closing unless I get annoyed with the current solution and decide to revisit in a sophisticated way.

**Comment by CelticMinstrel** [comment]
To be clear, this was implemented in #351 and is thus done now… though you're welcome to find a better way to do it at some point, I don't think it's necessary. Pixellated text is kind of expected in Blades of Exile, in my opinion. (We'd ideally disable anti-aliasing on the text, but I'm not sure how to do that.)
