### ISSUE TITLE
Mac builds use dependencies built for MacOS 12

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#364]
The mac builds, while they work, probably only run on MacOS 12+, because we get our dependencies from brew, which doesn't support backwards-compatible dylib builds. We want to be building for a minimum of MacOS 10.9, which is why our Mac CI builds give us these warnings:

> ⚠️  ld: dylib (/usr/local/lib/libboost_system.dylib) was built for newer macOS version (12.0) than being linked (10.9)
> ⚠️  ld: dylib (/usr/local/lib/libboost_filesystem.dylib) was built for newer macOS version (12.0) than being linked (10.9)

A possible solution we talked about is to use a GitHub action such as [this one](https://github.com/egor-tensin/build-boost) to build boost from source in the Mac CI. Then we would want to cache these builds so the CI runs don't get tremendously slower.

**Comment by CelticMinstrel** [comment]
This is specific to the CI, so it's only an issue if we want to actually make the CI generate the artifacts.

**Comment by NQNStudios** [comment]
This action might be usable for building SFML from source: https://github.com/oprypin/install-sfml/

It doesn't have a README though...

**Comment by NQNStudios** [comment]
In my fork, I used these 2 github actions to solve this problem and I have the resulting build working on MacOS 10.15 (which I can actually test), but only for the scons build, not Xcode.

I wonder if I just changed the target to 10.13, this would also solve #192. I wouldn't be able to test it myself. Also we maybe don't need to fix #192, since it's been many years and maybe the interested parties are using newer macs now.

We should probably have a discussion about how to integrate this stuff into the CI -- because there is a meaningful distinction between CI that's intended to make sure the build works, and CI that's intended to produce a functioning and portable release build.

I also have my fork's build automatically signing and notarizing the app bundles, which is a requirement for Steam (not that a Steam release is anywhere close on the horizon for my fork) and it's using my personal Apple Developer membership credentials which cost $100/yr, so that part of the build probably shouldn't be contributed back to the upstream.

**Comment by CelticMinstrel** [comment]
> Also we maybe don't need to fix #192

Well, that's just an issue in the build itself, not in the code, so yes. I'd ideally like the game to be buildable on _any_ version of Mac OS X, but I don't really have the ability to test that effectively. With some work I might be able to test back to 10.4 at the earliest.

But, that's only about building; released binaries need not run on arbitrarily old macs. It would be nice if they can run on older ones, but not essential.

**Comment by NQNStudios** [comment]
Since the CI.yml workflow is just meant to test that the code builds and passes its tests, I feel ok closing this one.
