### ISSUE TITLE
Still using 100% cpu for a turn-based game that needs 0% cpu.

### ISSUE THREAD

**Issue by clort81** [calref/cboe#372]
There's no game logic running between turns / moves, at all.  It ran on a 20mhz 16-bit machine, originally.

So, has anyone done a fork that fixes this?

Please link if there is one.

**Comment by CelticMinstrel** [comment]
I would guess that the chief reason for this may be the animated terrain, which is probably CPU-bound. Logically, that could probably be done on the GPU, though. I am not aware of anyone who has tried this or any other changes that could affect CPU usage, however.

**Comment by NQNStudios** [comment]
While recently going through startup code to fix #366, this part of the code flagged my attention:

https://github.com/calref/cboe/blob/5d7332562195d4a5db5547bb6797c143c506848c/src/game/boe.startup.cpp#L131
```
	while(sound_going(95)) {
		draw_splash(pict_to_draw, mainPtr, logo_from);
		handle_splash_events();
	}
```

This code will update/draw as many times per second as the processor and GPU can handle. Which is not good--typically a game will lock its frame rate to a maximum of 60 or 30 by delaying at the end of every frame if time was used than needed.

I don't know if BoE is running as fast as it can at all times, or just at startup, but if it is, that could definitely be the culprit.

**Comment by NQNStudios** [comment]
Ah, this could be limiting the frame rate: https://github.com/calref/cboe/blob/5d7332562195d4a5db5547bb6797c143c506848c/src/game/boe.main.cpp#L340

**Comment by CelticMinstrel** [comment]
> I suspect this _is_ the source of the problem

That loop is only during startup, so I'm fairly sure it can't be the source of a general problem.

**Comment by NQNStudios** [comment]
Yeah.

**Comment by NQNStudios** [comment]
I found another place where event loops are spun up without frame rate limiting:
https://github.com/calref/cboe/blob/c251fee834a2c078b51d852f117e1442fde85771/src/dialogxml/widgets/control.hpp#L326

For example:
https://github.com/calref/cboe/blob/c251fee834a2c078b51d852f117e1442fde85771/src/dialogxml/widgets/control.cpp#L218

Still I don't know if this explains anything.

**Comment by CelticMinstrel** [comment]
That would explain jumping to 100% CPU when you press and hold your mouse on something in a dialog. That isn't what's described here.

**Comment by NQNStudios** [comment]
I'm making a single issue to track CPU-related concerns: #450 

A fair amount of CPU problems have been fixed--it's possible the original problem which prompted this issue, is fixed.
