### ISSUE TITLE
Credits overhaul

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#377]
The in-game credits live here: [startanim.png](https://github.com/calref/cboe/blob/master/rsrc/graphics/startanim.png)

![startanim.png](https://raw.githubusercontent.com/calref/cboe/master/rsrc/graphics/startanim.png)

A ton of past contributors are missing from these credits, plus 40 new financial supporters.

I'd like a robust way to generate this image from a text file if there's not one already. At a very low-tech level, this could just be an ImageMagick script we run manually when we need to update the animation.

I also think it would be good to have this animation, when clicked on, expand into its own dialog where a taller viewing window of the scrolling is visible, possibly also scaled up.

**Comment by CelticMinstrel** [comment]
That's not the only in-game credits. There's also the About dialog. You should add the missing contributors there first. We can later figure out how to deal with this image.

I'm not quite sure, but I suspect it's using the Chicago font? Could also be Geneva Bold, possibly. If it's going to be dynamically generated, the question of what font to use will inevitably arise…

**Comment by NQNStudios** [comment]
I checked and the scrolling image font isn't Chicago.

**Comment by NQNStudios** [comment]
I think I was looking at the wrong dialog when I said the formatting was broken.

This is the About Dialog, which has a scrollbar and it's all formatted perfectly:

<img width="755" alt="Screenshot 2024-11-07 at 12 44 37 PM" src="https://github.com/user-attachments/assets/3134e425-17b3-4d8f-a53c-4f3bd45164ab">

The dialog with the broken format is the Intro dialog, not the About dialog, so I'll make an issue for that.

**Comment by CelticMinstrel** [comment]
I wonder, should we remove the emails from that list? There's a pretty decent chance that at least one of them is dead.

**Comment by NQNStudios** [comment]
Yeah I'll go ahead and remove the emails. Even the one I have for JV doesn't match the one that's in the dialogue, and I also don't think he'd want to be the point of contact for BoE inquiries anymore.
