### ISSUE TITLE
Scenario list is also non-deterministic in replays

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#392]
Replays track which scenario you open only through the ui events for paging forward/backward in the scenario list and which of the 3 buttons you click on.

So, if you run a replay with a different set of custom scenarios installed, the replay could end up choosing to open the wrong scenario.

This is a very nasty problem, I haven't figured out how to solve it in a way that isn't crazy.

Totally crazy solution:
* When recording the start scenario action, compress the custom scenarios folder into one file and base64-encode it into the replay log.
* When replaying the start scenario action, decode and extract the recorded custom scenarios into the temporary directory, and read the scenario list from there instead of the user's custom scenario folder

**Comment by NQNStudios** [comment]
Less crazy solution: record the user's scenario list into the replay log. When replaying, check the custom scenario list for equality to the recorded list. If the list is different, print an error telling which custom scenarios are required and which need to be removed for compatibility with that replay.

**Comment by CelticMinstrel** [comment]
Even less crazy: record the user's scenario list into the replay log. When replaying, use that list to determine what show in the UI, _even if some of the scenarios in question are not installed_. Just substitute the question mark icon and a "scenario missing" text for any scenarios that are not installed.

**Comment by NQNStudios** [comment]
Good call. And if the replay tries to launch a missing scenario, then display an error.

**Comment by CelticMinstrel** [comment]
Yeah, of course.
