### ISSUE TITLE
alt+start scenario records incorrectly in replays

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#394]
I didn't realize the alt-key is significant when clicking startup buttons. need to make that replay action record its state

**Comment by NQNStudios** [comment]
Should probably refactor `handle_startup_button_click` so it takes modifiers as a parameter the way dialog click events do, instead of calling `kb.isAltPressed()` in its body

**Comment by CelticMinstrel** [comment]
Is alt the only modifier that's significant here? I remember there's a modifier you can hold to get the debug preset party instead of the default preset party… but now that I think of it, I guess that's in a dialog, not at startup…

**Comment by NQNStudios** [comment]
That was the only instance of using `kb` in `handle_startup_button_click()`.
