### ISSUE TITLE
wxWidgets port fails to buid against unicode wx

### ISSUE THREAD

**Issue by sylae** [calref/cboe#4]
_Original author: esw...@gmail.com (July 14, 2010 18:47:12)_

Using Debian's built-in version of libwx (2.8.7.1-1.1+lenny1), the experimental wxWidgets ports of the game and the character editor fail to build.  GCC instead throws numerous errors about failing to convert between wxString and char*.

I have tried to pass &quot;--unicode=no&quot; to wx-config, but it complains about having no matching library.

I have a patch that repairs the errors for the Character Editor, which I could either attach here or (with appropriate permissions) check in directly.  It uses the standard wxT macro where appropriate, and switches the rest on the wxUSE_UNICODE flag, so it should still build against non-unicode libraries.

I am willing to apply the same treatment to the game directory, too.

_Original issue: http://code.google.com/p/openexile/issues/detail?id=26_

**Comment by CelticMinstrel** [comment]
The wx port is defunct, as I opted instead to use SFML with a few native (Cocoa/WinAPI) add-ons. Thus I'm closing this.
