### ISSUE TITLE
Done shopping from Hamer: Crash.

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#420]
On Mac, in VoDT, when I shop with Hamer (the party is at full health, I don't know if this is significant) -- Every time I click Done, the game crashes.

Here's a save file right next to Hamer: [NextToHamer.exg.zip](https://github.com/user-attachments/files/16821781/NextToHamer.exg.zip)

And, compatible with https://github.com/NQNStudios/cboe/commit/369ebdfcd7849919ca97544e5e47342b31d08d17 here is a replay transcript that reproduces the crash reliably on my computer: 

[TalkHamerCrash.xml.zip](https://github.com/user-attachments/files/16821800/TalkHamerCrash.xml.zip)

This bug affects the current state of `master`, as well.

**Comment by CelticMinstrel** [comment]
This looks _very_ weird. I don't understand why that would fix it. But if it _does_ fix it then let's merge it.
