### ISSUE TITLE
The "don't understand" response doesn't seem to work.

### ISSUE THREAD

**Issue by CelticMinstrel** [calref/cboe#427]
For example, ask "Commander Terrance" in Fort Talrus about "bugs". The result is a blank response, instead of "He looks confused".

**Comment by NQNStudios** [comment]
I was thinking this might be happening for similar reasons to #420 https://github.com/calref/cboe/pull/421/commits/051130a4e1b293dcbf02842600fb3c20890a680e

**Comment by CelticMinstrel** [comment]
Fixed by #467
