### ISSUE TITLE
When replaying, match the original advance_time() behavior

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#437]
This is that known bug in the replay system that I need to get around to fixing.

**Comment by NQNStudios** [comment]
My plan for this one, is to make a temporary commit which makes advance_time calls record as elements in the action log. Then I want to record a single "One-Of-Everything" action log--which should be useful for testing the system as a whole--and reference the log to see precisely which actions are followed by advance_time() calls. That way the fix for this is based less in hazy "read the code and try to figure it out and not miss any cases" reasoning, and instead based on ground truth runtime behavior.

**Comment by CelticMinstrel** [comment]
Don't forget that my recharge PR introduced something that probably isn't replayable yet. I was going to look into implementing that but haven't gotten around to it.

**Comment by NQNStudios** [comment]
@CelticMinstrel what do you think of a CLI argument, default false, which records the advance_time() calls in the log? In replay, an <advance_time> element could indicate a replay-time assertion that the next thing to happen is an advance_time() call. This way when adding new actions/etc. we have a way to validate that advance_time behavior stays matched.

**Comment by CelticMinstrel** [comment]
Seems like an odd idea, but I can't think of any particular objections to it.

**Comment by NQNStudios** [comment]
Having implemented it, I can say it was a good idea. (PR coming soon.)

I'm going to call the flag `--verbose` and if we ever want to put more internal debugging information into logs, they can be implemented under the same flag.
