### ISSUE TITLE
Record the Blades of Exile version producing the action log

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#440]
This should help with debugging

**Comment by CelticMinstrel** [comment]
Maybe include both the version number (currently fixed at 2.0.0) and the git commit hash? And probably something like a "modified" tag if git is not clean.

I'd put it as attributes on the root element.

**Comment by NQNStudios** [comment]
I'm maintaining different tags in my fork than the ones here--and also, to make it clear when someone recorded an action log from their own fork, I'm also going to record the output of `git remote get-url origin`
