### ISSUE TITLE
win-scons debug builds don't actually have debugging symbols

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#444]
I can't figure out why this is the case, but the win-scons build doesn't actually create `.pdb` files for the individual object files, *or* for the final linked executables. The CCFLAGS we pass are correct, and are being used at compile-time. There is a `/DEBUG` link flag on Windows which we aren't passing, but I tried locally with that flag and it didn't help.

**Comment by NQNStudios** [comment]
https://learn.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=msvc-170
> If you compile a file outside of a project, the compiler creates a PDB file named VC<x>.pdb, where <x> is a concatenation of the major and minor version number of the compiler version in use

I actually do have a vc140.pdb file in the root of my clone... so maybe that's it, but we need to copy it over with the exes in order to debug them?

**Comment by NQNStudios** [comment]
>An executable (an EXE or DLL file) created for debugging contains the name and path of the corresponding PDB.

If this is true, I'm baffled

**Comment by CelticMinstrel** [comment]
But we're not compiling outside of a project, are we?

**Comment by NQNStudios** [comment]
2 things are so frustrating:

1. I do think the symbol file is being *created*, but not found and used when I open the binary to debug in Visual Studio. But the documentation says *the path where it's created should be recorded in the binary*, meaning we shouldn't have to pass a path to it.
2. I have also tried building with `/Z7` which claims it puts the symbols directly into the binary. *Still,* when I open that binary in Visual Studio it doesn't show debugging symbols.

**Comment by CelticMinstrel** [comment]
I meant passing a path to the compiler about where to create it, not passing a path to the binary about where to find it.
