### ISSUE TITLE
Legacy Win32 code

### ISSUE THREAD

**Issue by sylae** [calref/cboe#45]
As far as I am aware the Win32/ folder does nothing with New BoE. Why are we keeping it around in the current master branch? It might be in our interest to remove this code from master -- Perhaps branch it off to a `legacy-Win32` branch or something.

**Comment by CelticMinstrel** [comment]
Done! The contents of the Win32 folder is now in the legacy-win32 branch including its entire history. The Win32/ directory may now be safely deleted as long as two things are accounted for:

1. The Character Editor resource script in rsrc/menus still references an icon in the Win32 directory.
2. The Jenkins build script will need to be updated as well.

That was surprisingly easy, thanks to github's handy help explaining how to use `git filter-branch`.

**Comment by CelticMinstrel** [comment]
I've moved the icons to rsrc/legacy and removed the Win32 directory. Now all that's left is updating the Jenkins build script.

I'll let you decide whether this should be closed now.
