### ISSUE TITLE
Default graphics/UI scale >1?

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#468]
I think given modern monitor sizes, players are more likely than not to have extra space for the game window. Launching it at 1x scale can actually put strain on the eyes--and people might not think to go to the preferences to fix that. Maybe we could make the default setting 1.5x or even 2x?

**Comment by NQNStudios** [comment]
The base resolution is 605x430. 1.5x is 908x645. 2x is 1210x860.

These are the single-monitor resolution results of Valve's 2024 Hardware survey for Steam users:

![image](https://github.com/user-attachments/assets/2fe4e7ae-9d3d-42b7-9316-7d1c2634f685)

According to these results, the vertical dimension is the only thing holding us back from safely using 2x as the default.

1.5x would be a safe default for everyone on the survey except the non-standard vertical resolution 800x1280, and possibly some in the Other category.

The Steam survey isn't definitive, but I think it's a good baseline.

**Comment by NQNStudios** [comment]
We could even write code to just detect the largest scale that fits on the screen, and default to that one.

**Comment by NQNStudios** [comment]
Since I think the same scale pref is applied to the 2 editors, those resolutions are a consideration too.

PC editor: 590x440
Scen editor: 584x420

**Comment by CelticMinstrel** [comment]
Personally I think there's little point in doing something like this, unless we can write code that dynamically chooses somehow. Querying the screen's dpi somehow would be ideal, but basing it on what'll fit sounds okay too.
