### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by akien-mga** [calref/cboe#48]
Hi there,

Just wanted to drop a line to ask if there are any plans to add Linux support in the future? I'm not proposing to help with it myself (at least not as a coder, but I can of course do some testing) as I'm involved in many open source projects already, but I guess it's worth asking anyway what is the current status on this topic, if any.

I see there were attempts at a Linux port years ago: http://spiderwebforums.ipbhost.com/index.php?/topic/11210-blades-of-exile-for-linux-d/

**Comment by CelticMinstrel** [comment]
The Windows version currently works under WINE, so I don't consider it high priority. I'd certainly like to have a native Linux version, but it would require more familiarity with Linux GUI work than I currently have.

**Comment by CelticMinstrel** [comment]
There is now a linux branch here on the repository which appears to work fairly well on Linux (I was testing on Fedora 25). However, it's still incomplete - certain UI-related functions are just stubs at the moment, and in particular, there are no menus. Also, my desktop manager often erroneously believes the program has stopped responding, which is something that would need to be fixed somehow before merging the branch.

**Comment by akien-mga** [comment]
Nice work! I tested it on Mageia 6 and it builds fine out of the box. As you mention, it does not appear to be fully functional yet, but I'm looking forward to test the progress on that branch :)

**Comment by CelticMinstrel** [comment]
Working on it slowly, starting by implementing the general stubs. 86bf93c9c5584d4a98023dd14e4f12e3b42e6c7f Maybe you can tell that I don't really know what I'm doing. (That commit doesn't compile, so don't bother trying it.)

**Comment by absquatulate** [comment]
Attached a quick diff to get your latest commit going. I've also included an option for scons to generate debug symbols. We can now load and save parties using a quick hack.

[linux.zip](https://github.com/calref/cboe/files/889558/linux.zip)

**Comment by CelticMinstrel** [comment]
Thanks! Would've been easier if you submitted it as a pull request, though. In any case, I'll apply it sometime in the next few days, probably.

**Comment by absquatulate** [comment]
Good point, I have made a pull request now. Will keep working on it slowly.

**Comment by CelticMinstrel** [comment]
Random thought, since it was made to use zenity for file dialogs, maybe it could use the zenity list dialog as a substitute for menus. It's not an ideal solution, I guess, but may be better than having _no_ access to those commands. (Would also require manually implementing all the accelerator keys into the key input handling routine _only_ on the Linux build.)

**Comment by CelticMinstrel** [comment]
Linux support is still missing a few implementations in winutils.linux.cpp (plus menus and custom cursors), but since it's essentially functional, this can be closed.
