### ISSUE TITLE
Light mask visual offset errors

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#493]
<img width="562" alt="Screenshot 2024-11-24 at 3 47 53 PM" src="https://github.com/user-attachments/assets/be51d16a-52b3-4d6b-ad1e-aa9612a6e308">

<img width="562" alt="Screenshot 2024-11-24 at 3 48 50 PM" src="https://github.com/user-attachments/assets/6e188da7-0a58-4cde-8700-ae837fc084d2">

You can see the mask overlapping the terrain window's border on the left, and you can see parts of tiles on the right which should be covered (in the second screenshot, the walls on the right). Also, the ellipses and some flat edges form weird jagged connections (see the north part of both).

**Comment by NQNStudios** [comment]
I realized I have to make sure this affects master and wasn't caused by my changes in PR #494.

**Comment by NQNStudios** [comment]
The discussion on #32 seems to indicate that issue is fixed already. I can look into it while investigating this one.

**Comment by fosnola** [comment]
I just looked at the differences with my code, which seems to give slightly better results:
[graph.patch](https://github.com/user-attachments/files/17966078/graph.patch)

**Comment by fosnola** [comment]
This gives:
<img width="557" alt="Capture d’écran 2024-11-30 à 17 38 03" src="https://github.com/user-attachments/assets/0c363fa7-b9d9-4fd9-80fc-0f55e94d5d2c">
<img width="565" alt="Capture d’écran 2024-11-30 à 17 36 57" src="https://github.com/user-attachments/assets/ae47ad75-e79c-477a-8f84-15086e4bdd3c">

**Comment by fosnola** [comment]
It's quite complicated for this little patch that changes a rectangle in boe.newgraph.cpp, the rectangle clipping and the position where the oval is displayed.
Normally, all you need to do is `git apply graph.patch` : see https://stackoverflow.com/questions/5159185/how-to-create-a-git-patch-from-the-uncommitted-changes-in-the-current-working-di

**Note :** The bottom of the ovals is not displayed correctly with this patch ( but it's not too noticeable )

**Comment by NQNStudios** [comment]
Okay, I'll handle making the PR, credit you as coauthor, and see if I can fix the bottom of the ovals if that's okay.

**Comment by fosnola** [comment]
Okay

**Comment by NQNStudios** [comment]
Could you send me your email address, or your anonymized github email address, so I can link the commit correctly with you? https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by fosnola** [comment]
I'm not sure how to find the anonymized github email address GitHub address, but this one works : osnola@users.sourceforge.net .

**Comment by NQNStudios** [comment]
I'm going to spin off a new issue for the 2nd part of this problem, because I've found out it's really thorny.
