### ISSUE TITLE
Icy rain spell is (mostly?) implemented but not castable?

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#497]
In the code I'm seeing that there's a spell called icy rain that is either only partially implemented, or fully implemented but not wired into the spellcasting menu. Do we want it?

(It also drops ashes on the target square, which seems wrong, so I'm going to fix that regardless of whether we add it in.)

**Comment by NQNStudios** [comment]
Like, I can *kind of* imagine the icy rain scours the ground so it leaves something that looks like ashes? But does it really make sense? idk.

**Comment by CelticMinstrel** [comment]
Looks like it's one of several new spells I added in 5364d9cb6. I would say it doesn't need to be in the spellcasting menu – even without being accessible there, it can easily be attached to an item.
