### ISSUE TITLE
Text box in talking mode doesn't go away when changing preferences while in talking mode

### ISSUE THREAD

**Issue by sylae** [calref/cboe#5]
_Original author: portra...@lavabit.com (July 14, 2011 12:03:31)_

<b>What steps will reproduce the problem?</b>
1. In Windows go to preferences, then select &quot;Ask about text box in talking mode&quot;, then, in the game, walk up to someone and talk to them.  Then, while still in talking mode, go back to preferences, deselect the option and exit talking mode.

<b>What is the expected output? What do you see instead?</b>
The text box is supposed to disappear.  Instead it stubbornly remains on the screen, even when you aren't in talking mode, until you exit the game.  Going back to preferences and selecting/deselecting the option does not help.

<b>What version of the product are you using? On what operating system?</b>
Win32_CBoE_build_05.02.2011 on Windows XP Home Edition SP 3

<b>Please provide any additional information below.</b>
I'm sure it's a very small issue that I'm surprised I even came upon (I know, I do weird stuff when I'm checking out new features), but still, I think it couldn't hurt to fix it.

BTW, great job with all the work you guys did on improving the game.  Glad to see my favorite game didn't disappear into long lost history. :)

_Original issue: http://code.google.com/p/openexile/issues/detail?id=28_

**Comment by CelticMinstrel** [comment]
The text box has actually been removed, so I'm going to close this. If its return is desired, a new issue can be opened for that.
