### ISSUE TITLE
Implement "Use" for the outdoors.

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#503]
As I discovered when investigating #8, the terrain "Call special when used" feature is designed to support local outdoor special nodes. It won't let the designer use a local special node definition unless every outdoor section implements the node, too.

Which is incongruent with the fact that you *can't use any terrains* outdoors right now. So we have two logical choices:

* Implement "use" for the outdoors (would this have sweeping consequences and require a lot of design/thought? It would definitely require adding a button to the outdoor toolbar.)
* Remove the restriction in the editor that requires outdoor sections to implement the local node. Local "use" nodes will only be used in towns.

**Comment by CelticMinstrel** [comment]
I guess I'm leaning towards option 2, as it seems to be simpler.

**Comment by NQNStudios** [comment]
I'd be okay with that. I figure design-wise that it was intentional to exclude "Use" from the outdoors. Because the outdoors are supposed to be at a larger scale where you're not looking at a lever or a door, you're looking at a swath of land, which is not something you would "use".
