### ISSUE TITLE
Request for Release of Open Blades of Exile instead of Classic Blades of Exile

### ISSUE THREAD

**Issue by ribbybbir** [calref/cboe#504]
Is it ironic/hypocritical to see that the OBoE project is still using CBoE instead of using a OBoE fork? Isn't the Blades of Exile source code now free and open source? For all calls of availability, I don't even see a release of this repository. I will assume that this project is still in its alpha development stage.

Actually, I did find releases on this webpage https://pentalithia.ca/oboe/. Yes, they are experimental, but the source code should be open for review. I used virustotal.com to scan for malware. Apparently, the Windows build have more malware than its Macintosh counterpart.

---

In addition, I read that Realmz was another rpg to be released free like Blades of Exile. Is there a chance to open its source code? I would like to see continued development of Realmz/Divinity despite the discontinued support of earlier Macintosh/Apple operating systems. OBoE, Realmz/Divinity, and Dark Disciples are free rpgs that should try cross-platform compatibility. I think that Linux is a great way to help develop that progress. Since OBoE is open source, it could be the base for similar games.

**Comment by NQNStudios** [comment]
This repository *is* Open Blades of Exile.

**Comment by NQNStudios** [comment]
I'm honestly taken aback by what I read as an accusatory tone followed by a request to release and port the source code for 3 totally different games that we don't have the rights to in any way, shape, or form.

This is the repository those experimental builds came from. No source code has ever been kept private.

> I will assume that this project is still in its alpha development stage.

This is correct, but why would you assume when you can ask politely?

**Comment by CelticMinstrel** [comment]
> Actually, I did find releases on this webpage https://pentalithia.ca/oboe/. Yes, they are experimental, but the source code should be open for review. I used virustotal.com to scan for malware. Apparently, the Windows build have more malware than its Macintosh counterpart.

Those releases were built from this repository. The repository is called cboe for historical reasons, but the project is called Open Blades of Exile.

I think it's possible to change the repository's name, but no-one has bothered. I suspect I'm not even the one who has the authority to do so. It also doesn't seem all that important.

The other games you mentioned have absolutely nothing to do with us. It's true that at one point Realmz and Exile were distributed by the same company (FantaSoft, I think it was called?) but there is no relation between them.
