### ISSUE TITLE
High-level spellcasting crash

### ISSUE THREAD

**Issue by NQNStudios** [calref/cboe#511]
Cast a spell on the 2nd page (ie firestorm), and the next time you try to cast that spell type the game will crash. I think I know exactly what's happening.

**Comment by fosnola** [comment]
<img width="1119" alt="Capture d’écran 2024-12-01 à 18 36 39" src="https://github.com/user-attachments/assets/2437d5a1-9592-46e2-8b05-2a50dec64533">
You call `const cSpell& operator*(eSpell spell_num)` with NONE. I suppose that if you replace `cSpell::dictionary.at(spell_num)` by `cSpell::dictionary[spell_num]`, this will work, ie. this will create a default cSpell for NONE and will return it. But it may be better to force the definition of cSpell::dictionary[NONE] before.
