### ISSUE TITLE
Update scons script to allow partial builds

### ISSUE THREAD

**Issue by CelticMinstrel** [calref/cboe#52]
At the moment, the scons script is all-or-nothing. It compiles all three programs and the test suite, copies all assets over to an install directory (within the build directory), runs the tests, and possibly even builds an install package (I was planning for that, can't remember if it was committed). There's no option to skip the tests, for example. There's no option to build just the scenario editor. There's also no option in the Linux branch to build with GCC instead of clang; I don't think there's an option for GCC _or_ clang when building on Windows.

All of this should be fixed. You should be able to type things like `scons scened` and get just the scenario editor (and, obviously, anything it depends on, which includes the base scenario and all assets).

**Comment by wrldwzrd89** [comment]
Related, the scons build script fails on macOS with a resource temporarily unavailable error; restarting the script results in a successful build. This happens after the disk image gets created, during what I assume is the finishing up phase of building.

**Comment by CelticMinstrel** [comment]
I've seen these errors on Travis too. No idea what to make of them. Googling suggests it might be something to do with non-blocking IO or something, but I don't really know. Since it's only temporary and doesn't even happen on my computer, and I managed to find a way to avoid it on Travis, I don't really feel motivated to track down the cause.
