### ISSUE TITLE
Buttons Not Working

### ISSUE THREAD

**Issue by absquatulate** [calref/cboe#53]
Buttons at the bottom of the screen no longer work, clicking has no effect.

Tested in both Windows and Linux.

**Comment by CelticMinstrel** [comment]
Does it depend on the display mode? The display mode is the position setting (or windowed mode) chosen in preferences. I generally test in windows mode, so if it does depend on the display mode I would tend to miss it.

**Comment by wrldwzrd89** [comment]
I reported this issue for Mac. I believe it was fixed already, but I don't know that fix's impact on Windows or Linux.

**Comment by absquatulate** [comment]
It does seem to depend on display mode: full screen mode doesn't work at all and windowed mode has incorrect click boundaries for each button. I can click much further to the right of a button to select it. An obvious example would be to click the left side of the 'U' character on the 'Use' button. Clicking there selected the 'Get' button.

**Comment by CelticMinstrel** [comment]
This should be fixed by 9c69e00.
