### ISSUE TITLE
Saving During Scenario Not Working

### ISSUE THREAD

**Issue by absquatulate** [calref/cboe#55]
After creating a party, saving and entering a scenario, saving (with Ctrl+S) and reloading that save takes me back to the main menu with my party loaded instead of in the scenario. The save file appears not to have been written to since the first save after party creation.

If I select the 'save as' option it seems to save correctly (first file is only 2kb but the second is now 26kb), but reloading the larger save causes the game to crash.

Tested on Windows, V2.0.0 [eedd4cd].

**Comment by CelticMinstrel** [comment]
Fixed in 513d926032d6038cbb28a27f71ce94acf798ffcd
