### ISSUE TITLE
Items bought from shops may be unidentified

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#65]
This is an item logged from the To-Do. If you are familiar with or can recreate this bug, please provide details here.

Can at least confirm as I have encountered this in my debug build on the latest commit.

**Comment by x-qq** [comment]
I have looked into this a little bit. The problem is caused by the following:
* refreshItems() in shop.cpp fills the shop inventory using data taken straight from scenario's items.xml
* not all items in items.xml (VoDT one for example) have identified property set

**Comment by wrldwzrd89** [comment]
Well, do we want to mark these items sold in shops as identified? If so, do they drop anywhere we do NOT want them identified? If YES and NO, this is a simple matter of updating items.xml. Otherwise, the fix is a bit more complex.

**Comment by CelticMinstrel** [comment]
Most items should not have the identified property set in items.xml - that property means "always identified" and is reserved for very common items.
