### ISSUE TITLE
Right clicking a node chain in-game shows you the node that will run in the text area, instead of running it like you're Looking.

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#80]
Actually it steps through. I think it's a result of using the character editor without closing the launcher.

---
This is an item logged from the To-Do and was originally reported by ADoS. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment]
It sounds to me that ADoS had accidentally activated trace mode. That said, if this can be confirmed as a bug _without_ having explicitly enabled debug mode and trace mode, feel free to reopen.
