### ISSUE TITLE
Fix display of special spots

### ISSUE THREAD

**Issue by sylae** [calref/cboe#9]
_Original author: celtic.m...@gmail.com (May 23, 2009 02:49:13)_

There are two problems currently with the display of white special spots.
The first, and most obvious, is that for some reason they are not drawn
transparent, meaning that they are on a white background that obscures the
underlying terrain. The other problem is that sometimes a special spot will
show up where there is no special. In the most extreme case, several rows
of special spots will appear over the entire visible terrain area.

_Original issue: http://code.google.com/p/openexile/issues/detail?id=14_

**Comment by CelticMinstrel** [comment]
I'm pretty sure this has finally been fixed.
