### ISSUE TITLE
Missing monsters

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#95]
Aren't there supposed to be rats in that hidden path in Fort Talrus, in the northwest? Commander Terrence isn't there either.

---
This is an item logged from the To-Do and was originally reported by ADoS. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment]
Given how egregious this it, I imagine it's probably fixed. (Yes there are supposed to be rats there.)

**Comment by CelticMinstrel** [comment]
I'm pretty sure this is fixed. If anyone notices missing monsters again, we can reopen it.
