### ISSUE TITLE
Crash when using rectangle fill tool

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#98]
I set surface terrain, but the starting town is cave floor.
I used the rectangle fill tool to make it all grass, and the scenario editor crashed.

---
This is an item logged from the To-Do and was originally reported by ADoS. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment]
If I recall correctly, this was caused by an out-of-bounds flood-fill and has been fixed.

It's possible I'm confusing it with a slightly different bug though.

**Comment by CelticMinstrel** [comment]
Neither rect fill nor flood fill causes a crash for me.
