### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#99]
"Failed to initialized automap!"
Logs say
`Testing cout Testing cerr "C:/Games\Spiderweb Software\Blades of Exile"`
Then, 28 times, it says
`Impossible to create render texture (failed to link the target texture to the frame buffer)`

---
This is an item logged from the To-Do and was originally reported by ADoS. If you are familiar with or can recreate this bug, please provide details here.

**Comment by x-qq** [comment]
This looks like opengl implementation is missing.

**Comment by CelticMinstrel** [comment]
I believe ADoS was running the Windows implementation under WINE when he got this error, tho I'm not 100% sure.

**Comment by CelticMinstrel** [comment]
Closing because I'm pretty sure this was just something wrong in the WINE setup.
